package com.lbb.clothes.business.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.github
     *
     * @mbg.generated
     */
    private String github;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.wx_img
     *
     * @mbg.generated
     */
    private String wxImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.id
     *
     * @return the value of blog_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.id
     *
     * @param id the value for blog_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_name
     *
     * @return the value of blog_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_name
     *
     * @param userName the value for blog_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.name
     *
     * @return the value of blog_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.name
     *
     * @param name the value for blog_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.password
     *
     * @return the value of blog_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.password
     *
     * @param password the value for blog_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.github
     *
     * @return the value of blog_user.github
     *
     * @mbg.generated
     */
    public String getGithub() {
        return github;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.github
     *
     * @param github the value for blog_user.github
     *
     * @mbg.generated
     */
    public void setGithub(String github) {
        this.github = github;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.qq
     *
     * @return the value of blog_user.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.qq
     *
     * @param qq the value for blog_user.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.email
     *
     * @return the value of blog_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.email
     *
     * @param email the value for blog_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.remark
     *
     * @return the value of blog_user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.remark
     *
     * @param remark the value for blog_user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.img
     *
     * @return the value of blog_user.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.img
     *
     * @param img the value for blog_user.img
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.wx_img
     *
     * @return the value of blog_user.wx_img
     *
     * @mbg.generated
     */
    public String getWxImg() {
        return wxImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.wx_img
     *
     * @param wxImg the value for blog_user.wx_img
     *
     * @mbg.generated
     */
    public void setWxImg(String wxImg) {
        this.wxImg = wxImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.type
     *
     * @return the value of blog_user.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.type
     *
     * @param type the value for blog_user.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.create_time
     *
     * @return the value of blog_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.create_time
     *
     * @param createTime the value for blog_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}